### PR TITLE
Check accesses to the bookname_to_ifo std::map

### LINKED ISSUE #87: sdcv -u not_exists_dictonary = Internal error: map::at
```
 ./sdcv -u not_esists_dictionary
Internal error: map::at
```

### PR DESCRIPTION
**Pull request by NiLuJe**
Avoid crashes when passing unknown dicts to the -u flag

Fix #87

### CODE REVIEW

File: src/sdcv.cpp [hunk 1]
```diff
@@ -186,10 +186,11 @@ try {
...
         // add bookname to list
-        gchar **p = get_impl(use_dict_list);
-        while (*p) {
-            order_list.push_back(bookname_to_ifo.at(*p));
-            ++p;
+        for (gchar **p = get_impl(use_dict_list); *p != nullptr; ++p) {
+            auto it = bookname_to_ifo.find(*p);
+            if (it != bookname_to_ifo.end()) {
+                order_list.push_back(it->second);
+            }
```
Comment (Dushistov) [inline src/sdcv.cpp:193]: What about report to stderr and return EXIT_FAILURE if there are no such dictionary instead of silently ignore error in user supplied list?

File: src/sdcv.cpp [hunk 2]
```diff
@@ -201,7 +202,10 @@ try {
         if (ordering_file != nullptr) {
             std::string line;
             while (stdio_getline(ordering_file, line)) {
-                order_list.push_back(bookname_to_ifo.at(line));
+                auto it = bookname_to_ifo.find(line);
+                if (it != bookname_to_ifo.end()) {
+                    order_list.push_back(it->second);
+                }
```
Comment (Dushistov) [inline src/sdcv.cpp:208]: If there is error in file with list of dictionaries, may be better report that to user?

**Review by Dushistov — CHANGES_REQUESTED** [review]

File: src/sdcv.cpp (hunk 1 above)
Comment (NiLuJe) [reply src/sdcv.cpp:193]: That sounds sensible, but raises another question: should we abort early on *any* failure, or continue with a potentially limited dictionary list (if any)?

(Warning no matter what makes sense, though).

**Comment by NiLuJe** [comment]
Added warnings only for now, until a decision is made about how to handle a potential early exit ;).

**Review by Dushistov — APPROVED** [review]
I suppose that right way to handle error is aborting,
because of in the same works all console utilities like "ls", "cp" and so on.
If one of arguments not exists and required for work they abort and return not 0 exit code.

But this can be changed in other PR.

**Comment by Dushistov** [comment]
Thank you for PR.
