### PR TITLE
Store integer magic in cache file

### LINKED ISSUE #36: Test failures on big endian
Both fail with:

```
sdcv: /<<PKGBUILDDIR>>/src/stardict_lib.cpp:542: const gchar* {anonymous}::OffsetIndex::read_first_on_page_key(glong): Assertion `(nitems == 1)' failed.
```

Problematic code:

https://github.com/Dushistov/sdcv/blob/925a4bc163f181c762681c59082de9598a79ddd4/src/stardict_lib.cpp#L535-L545

* [mips build log](https://buildd.debian.org/status/fetch.php?pkg=sdcv&arch=mips&ver=0.5.2-1&stamp=1510155370&file=log)
* [s390x build log](https://buildd.debian.org/status/fetch.php?pkg=sdcv&arch=s390x&ver=0.5.2-1&stamp=1510155090&file=log)
* [powerpc build log](https://buildd.debian.org/status/fetch.php?pkg=sdcv&arch=powerpc&ver=0.5.2-1&stamp=1510156686&file=log)

### PR DESCRIPTION
**Pull request by nijel**
This allows to detect different endianity of machines to avoid
loading caches created with different endianity.

Fixes #36

### CODE REVIEW

File: src/stardict_lib.cpp [hunk 1]
```diff
@@ -573,7 +574,9 @@ bool OffsetIndex::load_cache(const std::string &url)
             continue;
         if (strncmp(mf.begin(), CACHE_MAGIC, strlen(CACHE_MAGIC)) != 0)
             continue;
-        memcpy(&wordoffset[0], mf.begin() + strlen(CACHE_MAGIC), wordoffset.size() * sizeof(wordoffset[0]));
+        if (*(guint32 *)(mf.begin() + strlen(CACHE_MAGIC)) != CACHE_MAGIC_BYTES)
```
Comment (Dushistov) [inline src/stardict_lib.cpp]: For some CPU it is bad to access 32bit word not via 32bit aligned pointer,
it would be better do something like:
```
guint32 tmp;
memcpy(&tmp, mf.begin() + strlen(CACHE_MAGIC), sizeof(tmp));
if (tmp != CACHE_MAGIC_BYTES) {
```

Comment (nijel) [reply src/stardict_lib.cpp]: Good point, patch updated.
